### PR TITLE
Update FresaClub.sol

### PR DESCRIPTION
**Pull request by 0xScratch**
This PR focuses on two main changes :

1. Enhancing the 'for' loop: Here's the [reference](https://gist.github.com/grGred/9bab8b9bad0cd42fc23d4e31e7347144#for-loops-improvement)
2. Structs Packing and changes in functions accordingly: [Refer this](https://dev.to/javier123454321/solidity-gas-optimizations-pt-3-packing-structs-23f4)

Thanks @MatWaller @aditya172926

### CODE REVIEW

**Comment by MathewWaller** [comment]
@Aryan9592 Hey - id accept this but i dont seem to have access to accept the push i will try reach out to ramiro who will be able to help.

**Comment by anhfactor** [comment]
Thanks for your help @Aryan9592

**Comment by MatWaller** [comment]
@anhfactor Thanks mate - I Had logged into the wrong account was wondering why i couldn't merge!

**Comment by MatWaller** [comment]
> This PR focuses on two main changes :
> 
> 1. Enhancing the 'for' loop: Here's the [reference](https://gist.github.com/grGred/9bab8b9bad0cd42fc23d4e31e7347144#for-loops-improvement)
> 2. Structs Packing and changes in functions accordingly: [Refer this](https://dev.to/javier123454321/solidity-gas-optimizations-pt-3-packing-structs-23f4)
> 
> Thanks @MatWaller @aditya172926

I have no issues with this - thanks.

**Comment by 0xScratch** [comment]
Seems like we should add some tests for this repo using foundry...What's your say about it? @anhfactor @MatWaller

**Comment by MatWaller** [comment]
@Aryan9592 Not a bad idea - This project is sleeping at the moment I have been meaning to come back round to it, thanks for reminding me!

**Pull request merged**
